### ISSUE TITLE
[BUG] 提示已生成实体类，但是在对应包下却没有实体类

### ISSUE THREAD

**Issue by xiaomifeng1010** [carter-ya/idea-plugin-jpa-support#64]
多次尝试生成实体类和repository类但是都提示类已存在，但是在项目的对应包下，什么也没有

**Comment by carter-ya** [comment]
![image](https://user-images.githubusercontent.com/18641671/89522195-634a1880-d813-11ea-811c-abf3982ea4e5.png)

应该是需要重新reload一下，你到磁盘相应文件夹下看看

**Comment by xiaomifeng1010** [comment]
解决了，创建到其他模块中去了，因为是微服务项目，所以保存到其他模块了，很奇怪，选择的是当前模块的package，但是生成到其他模块的包下了！

**Comment by carter-ya** [comment]
正在开发中的版本可以选择模块，可以解决这个问题



            
            
                
                    
                            
                                
                            
                            
                                liukefeng2008
                            
                    
                        
                            
                                    邮箱：liukefeng2008@hotmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            在2020年08月07日 09:04，xiaomifeng1010 写道： 

解决了，创建到其他模块中去了，因为是微服务项目，所以保存到其他模块了，很奇怪，选择的是当前模块的package，但是生成到其他模块的包下了！



—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/carter-ya/idea-plugin-jpa-support/issues/64#issuecomment-670264493",

"url": "https://github.com/carter-ya/idea-plugin-jpa-support/issues/64#issuecomment-670264493",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by xiaomifeng1010** [comment]
ok,还有一个问题就是，数据库中的字段是datetime类型，生成的实体类属性的类型的是jdk中sql包下的timestamp类型,而不是util包下的date类型

**Comment by carter-ya** [comment]
> ok,还有一个问题就是，数据库中的字段是datetime类型，生成的实体类属性的类型的是jdk中sql包下的timestamp类型,而不是util包下的date类型

这个会在未来的版本允许编辑数据类型映射关系

**Comment by huangsansui** [comment]
我也碰到了类似的问题，不过我不是多模块，我的项目是gradle构建的，生成时提示 Error: Module xxx does not contain Source Root. 在对应包下找不到文件，再次生成提示文件已存在，是否覆盖

**Comment by carter-ya** [comment]
> 我也碰到了类似的问题，不过我不是多模块，我的项目是gradle构建的，生成时提示 Error: Module xxx does not contain Source Root. 在对应包下找不到文件，再次生成提示文件已存在，是否覆盖

你这个情况是必现还是偶发呢，如果是偶发你可以使用这个地址解决下
https://github.com/carter-ya/idea-plugin-jpa-support/issues/64#issuecomment-669850310

**Comment by Aiurvie** [comment]
> 我也碰到了类似的问题，不过我不是多模块，我的项目是 gradle 构建的，生成时提示 Error: Module xxx does not contain Source Root. 在对应包下找不到文件，再次生成提示文件已存在，是否覆盖



我也碰到了这样的问题，但是文件生成在了 toolbox 的文件夹里面。
C:\Users\用户名\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\201.7846.76\jbr\bin

**Comment by carter-ya** [comment]
请更新最新版本
