### ISSUE TITLE
[BUG]Error: Generate source code error. java.lang.IllegalArgumentException: separators must be '/';

### ISSUE THREAD

**Issue by pansx** [carter-ya/idea-plugin-jpa-support#66]
**Describe the bug （描述这个Bug）**
无法生成,提示:
8:40	Error: Generate source code error. java.lang.IllegalArgumentException: separators must be '/'; path is C:\Users\pansx\IdeaProjects\sqltest\src\main\java\net\pansx\sqltest\entity
但是在ui上的配置确实是/...
**Expected behavior （期望的行为）**
正常生成
**Screenshots （截图，如果有的话）**
![QQ截图20200820084447](https://user-images.githubusercontent.com/6763939/90703836-75bb5c00-e2c1-11ea-86d8-e68cfddab384.png)

**idea version (idea的版本号):**
For example: IntelliJ IDEA 2019.3.3 (Ultimate Edition)
IntelliJ IDEA 2020.2 (Ultimate Edition)
**idea plugin jpa support version (idea plugin jpa support的版本号）:**
For example: 2.02

**Comment by carter-ya** [comment]
问题已收到，我复现一下



            
            
                
                    
                            
                                
                            
                            
                                liukefeng2008
                            
                    
                        
                            
                                    邮箱：liukefeng2008@hotmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


            On 08/20/2020 08:47, pansx wrote: 
Assigned #66 to @carter-ya.

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/carter-ya/idea-plugin-jpa-support/issues/66#event-3673081589",
"url": "https://github.com/carter-ya/idea-plugin-jpa-support/issues/66#event-3673081589",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by littlell** [comment]
+1， 也遇到了这个问题

**Comment by carter-ya** [comment]
@littlell  @pansx  请下载该版本尝试下是否能解决你的问题  https://github.com/carter-ya/idea-plugin-jpa-support/releases/download/v2.0.3/Jpa.Support-2.0.3.zip

**Comment by littlell** [comment]
> @littlell @pansx 请下载该版本尝试下是否能解决你的问题 https://github.com/carter-ya/idea-plugin-jpa-support/releases/download/v2.0.3/Jpa.Support-2.0.3.zip

试过了， 手动从磁盘安装这个插件， 还是有如下的错误提示， 好像没有修复

com.intellij.diagnostic.PluginException: com.ifengxue.plugin.action.JpaSupportWithDatabasePlugin (JPASupport.NewEntities3): group with id "DatabaseViewPopupMenu" isn't registered; action will be added to the "Other" group [Plugin: com.ifengxue.plugin.jpa-support]
