### ISSUE TITLE
关于生成实体列字段大小写问题

### ISSUE THREAD

**Issue by medzeus2** [carter-ya/idea-plugin-jpa-support#71]
场景：DB2 数据库

如果列名带“_”的字段生成是正确的
```java
  @Column(name = "STU_NAME", nullable = false)
    private String stuName;
```
但是如果是全英文不带下划线的字符，生成如下表所示，一般如果把生成的字段用于传输，都建议改为小写。
```java
    @Column(name = "TELPHONE", nullable = false)
    private String TELPHONE;
```
建议增加参数 控制生成字段默认大小写。

**Comment by carter-ya** [comment]
可以理解为当列名所有字符全为大写时，允许字段名全为小写




            
            
                
                    
                            
                                
                            
                            
                                liukefeng2008
                            
                    
                        
                            
                                    邮箱：liukefeng2008@hotmail.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年09月09日 14:03，zeus2 写道： 
场景：DB2 数据库
如果列名带“_”的字段生成是正确的
  @Column(name = "STU_NAME", nullable = false)
    private String stuName;
但是如果是全英文不带下划线的字符，生成如下表所示，一般如果把生成的字段用于传输，都建议改为小写。
    @Column(name = "TELPHONE", nullable = false)
    private String TELPHONE;
建议增加参数 控制生成字段默认大小写。

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/carter-ya/idea-plugin-jpa-support/issues/71",
"url": "https://github.com/carter-ya/idea-plugin-jpa-support/issues/71",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by carter-ya** [comment]
请更新最新版本
